# SPDX-FileCopyrightText: 2021 The ha-octopus-energy Authors
#
# SPDX-License-Identifier: 0BSD

[tool.isort]
# These settings ensure that black and isort don't disagree on the imports.
line_length = 88
multi_line_output = 3
include_trailing_comma = true

known_third_party = ['octopy_energy']
