# SPDX-FileCopyrightText: 2020 Paulus Schoutsen
#
# SPDX-License-Identifier: 0BSD

name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
